export const CHARACTER_LIST_REQUEST = 'CHARACTER_LIST_REQUEST'
export const CHARACTER_LIST_SUCCESS = 'CHARACTER_LIST_SUCCESS'
export const CHARACTER_LIST_FAIL = 'CHARACTER_LIST_FAIL'

export const CHARACTER_DETAILS_REQUEST = 'CHARACTER_DETAILS_REQUEST'
export const CHARACTER_DETAILS_SUCCESS = 'CHARACTER_DETAILS_SUCCESS'
export const CHARACTER_DETAILS_FAIL = 'CHARACTER_DETAILS_FAIL'