const characters = [
  {
    _id: '1',
    title: 'Unhallowed Essence',
    characterKlass: 'Demon Hunter',
    helm: 'Accursed Visage',
    shoulders: 'Demon Plate',
    gloves: 'Fiendish Grips',
    chestArmor: 'Cage of the Hellborn',
    belt: 'Witching Hour',
    pants: 'Holy Plate',
    boots: 'Hell Walkers',
    bracers: 'Wraps of Clarity',
    amulet: 'Hellfire',
    ring1: 'Focus',
    ring2: 'Restraint',
    weapon: 'Yangs',
    offhand: 'Dead Mans Legacy',
    gemNotes: 'Emeralds',
    kanaisCube: 'Dawn::Convention of Elements::Visage of Gunes',
    activeSkills: 'MultiShot',
    passiveSkills: 'Ballistics',
    generalBuildNotes: 'Tart jelly-o tart biscuit cotton candy I love candy canes. Pastry caramels dessert caramels cake brownie cookie halvah jelly beans. Marzipan dessert ice cream bonbon I love I love chocolate cake I love tart. I love candy canes chocolate bar marzipan. Tootsie roll sweet roll caramels cake sugar plum. Marzipan halvah sweet marshmallow biscuit ice cream muffin gummies. Oat cake jelly jelly I love. Cheesecake toffee lemon drops croissant bear claw danish biscuit I love topping. Topping biscuit sweet roll I love caramels. Tootsie roll candy pastry. Sweet roll tootsie roll lollipop pie chocolate cake biscuit bonbon topping. I love tiramisu tart marshmallow pie tootsie roll wafer liquorice gummies.',
    image: '/images/ue.jpg',
    rating: '5',
    numReviews: '200'
  },
  {
    _id: '2',
    title: 'Bone Cage',
    characterKlass: 'NecroMancer',
    helm: 'Bike Helmet',
    shoulders: '80s Shoulder pads',
    gloves: 'Bernies Mittens',
    chestArmor: 'Sweater Vest',
    belt: 'Rope',
    pants: 'BellBottoms',
    boots: 'Tims',
    bracers: 'Sweatband',
    amulet: 'Candy Necklace',
    ring1: 'Turquiose',
    ring2: 'None',
    weapon: 'Wit',
    offhand: 'Snarky',
    gemNotes: 'Stuffs',
    kanaisCube: 'My misery',
    activeSkills: 'Mouthy',
    passiveSkills: 'Bipolar',
    generalBuildNotes: 'Change Everything',
    image: '/images/necro.jpg',
    rating: '3.6',
    numReviews: '146'
  },
  {
    _id: '3',
    title: 'Holy Hellz',
    characterKlass: 'Crusader',
    helm: 'Another Helm',
    shoulders: 'Pauldrons',
    gloves: 'LEather',
    chestArmor: 'Bolied Leather',
    belt: 'Bungee Cord',
    pants: 'More Leather Stuff',
    boots: 'Bedroom Slippers',
    bracers: 'Wraps',
    amulet: 'Squirts',
    ring1: 'Poop',
    ring2: 'Cicle',
    weapon: 'Mjolnir',
    offhand: 'Shield',
    gemNotes: 'Diamonds',
    kanaisCube: 'Stuffs again',
    activeSkills: 'Ignorance',
    passiveSkills: 'NonCompliant',
    generalBuildNotes: 'Keep It',
    image: '/images/cru.jpg',
    rating: '4.3',
    numReviews: '900'
  },
  {
    _id: '4',
    title: 'Wizzy Wiz',
    characterKlass: 'Wizard',
    helm: 'Big Dumb Wizrd HAt',
    shoulders: 'Big Dumb Wizard Shoulders',
    gloves: 'Dumb Wizrd Gloves',
    chestArmor: 'Dumb Wizrd Armor',
    belt: 'Dumb Wizrd Belt',
    pants: 'Pants',
    boots: 'Boots',
    bracers: 'Bracers',
    amulet: 'Ammy',
    ring1: 'Wiz Ring',
    ring2: 'Dumb Wiz Ring',
    weapon: 'Snowball',
    offhand: 'Fire',
    gemNotes: 'Rocks',
    kanaisCube: 'Light',
    activeSkills: 'Sarcasm',
    passiveSkills: 'Pewps',
    generalBuildNotes: 'More Pewps',
    image: '/images/wiz.jpg',
    rating: '1.2',
    numReviews: '300'
  },
  {
    _id: '5',
    title: 'The Dumb',
    characterKlass: 'Dork',
    helm: 'Stuff',
    shoulders: 'Stuff',
    gloves: 'Stuff',
    chestArmor: 'Stuff',
    belt: 'Stuff',
    pants: 'Stuff',
    boots: 'Stuff',
    bracers: 'Stuff',
    amulet: 'Stuff',
    ring1: 'Stuff',
    ring2: 'Stuff',
    weapon: 'Stuff',
    offhand: 'Stuff',
    gemNotes: 'Stuff',
    kanaisCube: 'Stuff',
    activeSkills: 'Stuff',
    passiveSkills: 'Stuff',
    generalBuildNotes: 'Stuff',
    image: '/images/lil.jpg',
    rating: '.5',
    numReviews: '9000'
  },
]

export default characters